---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
  annotations:
    fluxcd.io/tag.hello-app: regexp:^[1-9].[1-9]$
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:2.0
